version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      TZ: America/Ceara
      MARIADB_ROOT_PASSWORD: lampi
      MARIADB_USER: docker
      MARIADB_PASSWORD: lampi
      MARIADB_DATABASE: bdtest
      MARIADB_ROOT_HOST: '%'
    ports:
     - 8080:8080
    expose: 
     - 3308
    networks:
      - loja-network


  lojaonline:
    image: wirudev430/lojaonline
    restart: always
    build: ./lojaonline
    working_dir: /lojaonline
    environment:
      TZ: America/Ceara
      SPRING.DATASOURCE.URL: jdbc:mariadb://db:3305/bdtest
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: lampi
    ports:
     - 8080:8080
    command: mvn spring-boot:run
    depends_on:
    - db
    networks:
      - loja-network
networks:
  loja-network:
    driver: bridge