version: '3.1'

services:

  db:
    image: mysql:8.0.31
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Ceara
      MYSQL_ROOT_PASSWORD: lampi
      MYSQL_USER: docker
      MYSQL_PASSWORD: lampi
      MYSQL_DATABASE: bdtest
      MYSQL_ROOT_HOST: '%'
    ports:
     - 3305:3305
    expose: 
     - 3308
    networks:
      - loja-network


  lojaonline:
    image: wirudev430/lojaonline
    restart: always
    build: ./lojaonline
    working_dir: /lojaonline
    environment:
      TZ: America/Ceara
      SPRING.DATASOURCE.URL: jdbc:mariadb://db:3305/bdtest
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: lampi
    ports:
     - 8080:8080
    command: mvn spring-boot:run
    depends_on:
    - db
    networks:
      - loja-network
networks:
  loja-network:
    driver: bridge